### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by chrrox** [DenchiSoft/CubismViewerGems#1]
There is no option for pre multiplied alpha?
![CaptureAlpha](https://user-images.githubusercontent.com/10323815/111851716-bc6e4480-88ea-11eb-857f-1c8783c0ef62.PNG)

**Comment by chrrox** [comment]
![CaptureAlpha-2](https://user-images.githubusercontent.com/10323815/111852338-ef193c80-88ec-11eb-8ef1-63a7d70767a5.PNG)
How it looks with alpha

**Comment by DenchiSoft** [comment]
This project is no longer maintained because there is an official replacement. I may update the SDK from time to time, but there are now official builds from Live2D.

https://www.live2d.com/en/download/

On this page, download "Cubism Viewer for Unity".
